#!/bin/bash
# ^Batch script starts with shebang line

#SBATCH --ntasks=1                   # All #SBATCH commands need to be uninterrupted (by newlines too)
#SBATCH --nodes=1
#SBATCH --mem=20G
#SBATCH --gres=gpu:1
#SBATCH --time=01:00:00
#SBATCH --account=<KTR>
#SBATCH --job-name=fancyExp
#SBATCH --output=simulation-%j.out
#SBATCH --error=simulation-%j.err
#SBATCH --partition=capella-interactive  # my job is small

module purge                          # Set up environment, e.g., clean/switch modules environment
module load pytorch                   # load necessary modules

srun ./application [options]          # Execute parallel application with srun
