#!/bin/bash
# ^Batch script starts with shebang line

#SBATCH --ntasks=1                   # All #SBATCH commands need to be uninterrupted (by newlines too)
#SBATCH --cpus-per-task 1
#SBATCH --nodes=1
#SBATCH --mem=10G
#SBATCH --gres=gpu:1
#SBATCH --time=10:00
#SBATCH --account=p_scads_finetune
#SBATCH --job-name=lamp_finetuning
#SBATCH --output=simulation-%j.out
#SBATCH --error=simulation-%j.err
#SBATCH --partition=capella-interactive  # my job is small

module purge                          # Set up environment, e.g., clean/switch modules environment
# module load pytorch                   # load necessary modules

srun --gres=gpu:1 -c 1 --nodes=1 --mem=10G echo "Hello"
# srun ./application [options]          # Execute parallel application with srun
